package leetcode.String;

public class FindTheDifference {
    /**
     * Leetcode 389
     * You are given two strings s and t.
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     * Return the letter that was added to t.
     */
    static char findTheDifference(String s, String t) {
        int sumS = 0;
        int sumT = 0;
        for (char c : s.toCharArray()) {
            sumS += c;
        }
        for (char c : t.toCharArray()) {
            sumT += c;
        }
        return (char) (sumT - sumS);
    }
}
